config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :users, only: :show
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key], 
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol.upcase, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      nil
    end
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  
  def under_stock_limit?
    stocks.count < 10
  end
  
  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    'Anonymous'
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "You're following #{friend.full_name}!"
    else
      flash[:alert] = "There was something wrong with the tracking request!"
    end
    redirect_to my_friends_path
  end

  def destroy
    friend = User.find(params[:id])
    user_friend = current_user.friendships.where(friend_id: friend.id).first
    user_friend.destroy
    flash[:notice] = "#{friend.full_name} was successfully unfollowed!"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present? 
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search!"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search!"
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio!"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio!"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
  end

  def search
    if params[:friend].present? 
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user!"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a user to search!"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if user_signed_in?
      redirect_to my_portfolio_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_table.html.erb
<% if !@friends.empty? %>
  <div class="table-responsive-sm">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">E-mail</th>
          <th scope="col" class="text-center">Stocks</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%= count += 1 %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.email %></td>
            <td class="text-center"><%= friend.stocks.count %></td>
            <% if true %>
              <td class="text-center px-0">
                <%= link_to (fa_icon 'eye'), user_path(friend), class:"btn btn-primary btn-sm", title:"Follow User" %>
                <%= link_to (fa_icon 'trash'), friendship_path(friend), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger btn-sm", title:"Remove" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
  <div class="container">
    <%= link_to 'Finance Tracker', root_path, class:"navbar-brand font-weight-bold" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class:"nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My Friends', my_friends_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              <%= (fa_icon 'user') + " " + current_user.full_name %>
            </a>
            <div class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
              <%= link_to ((fa_icon 'edit') + " Edit Profile"), edit_user_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to ((fa_icon 'trash') + " Delete User"), user_registration_path, method: :delete, data: { confirm: "Are you sure?" }, class:"dropdown-item text-danger" %>
            </div>
          </li>
          <li class="nav-item m-1">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-danger btn-sm" %>
          </li>
        <% else %>
          <li class="nav-item m-1">
            <%= link_to 'Login', new_user_session_path, class:"btn btn-primary" if request.path != new_user_session_path %>
          </li>
          <li class="nav-item m-1">
            <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-success" if  request.path != new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container my-4">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_table.html.erb
<% if !@stocks.empty? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Ticker</th>
        <th>Company Name</th>
        <th>Price</th>
        <th colspan="2" class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% count = 0 %>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= count += 1 %></td>
          <td><%= stock.ticker %></td>
          <td><%= stock.name %></td>
          <td><%= number_to_currency(stock.last_price) %></td>
          <td class="text-center">
            <% if current_user.can_track_stock?(stock.ticker) %>
              <%= link_to (fa_icon 'plus'), user_stocks_path(user: current_user, ticker: stock.ticker), method: :post, class:"btn btn-success btn-sm", title:"Add Stock" %>
            <% elsif current_user.id != @user.id %>
              <span class="badge bg-secondary text-white">
                You're already tracking
                <% if !current_user.under_stock_limit? %>
                  10 stocks!
                <% elsif current_user.stock_already_tracked?(stock.ticker) %>
                  this stock!
                <% end%>
              </span>
            <% end %>
          <% if current_user.id == @user.id %>
              <%= link_to (fa_icon 'trash'), user_stock_path(stock), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger btn-sm", title:"Remove" %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5>Not tracking any stocks!</h5>
<% end %>

app/views/users/_friend_result.html.erb
<%= render 'layouts/messages' %>

<% if @friends %>
  <div class="card shadow mb-4">
    <table class="table table-bordeless">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong><%= friend.full_name %></td>
            <td><strong>Email: </strong><%= friend.email %></td>
            <td class="px-0">
              <%= link_to (fa_icon 'eye'), user_path(friend), class:"btn btn-primary btn-sm", title:"View Profile" %>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= link_to (fa_icon 'plus'), friendships_path(friend: friend), method: :post, class:"btn btn-warning btn-sm", title:"Follow User" %>
              <% else %>
                <%= fa_icon 'check', class:"btn btn-success btn-sm", title:"You're already friends!" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = "<%= escape_javascript(render 'users/friend_result.html')  %>"

app/views/users/_result.html.erb
<%= render 'layouts/messages' %>

<% if @stock %>
  <div class="card bg-light mb-3" style="max-width: fit-content;">
    <h5 class="card-header">
      <strong><%= @stock.name %></strong> (<%= @stock.ticker.upcase %>)
    </h5>
    <div class="card-body text-center">
      <p class="card-text"><strong>Price: </strong><%= number_to_currency(@stock.last_price) %></p>
      <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), method: :post, class:"btn btn-success btn-sm" %>
      <% else %>
        <span class="badge bg-secondary text-white">
          You're already tracking
          <% if !current_user.under_stock_limit? %>
            10 stocks!
          <% elsif current_user.stock_already_tracked?(@stock.ticker) %>
            this stock!
          <% end%>
        </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= escape_javascript(render 'users/result.html') %>"

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="row">
  <div class="col-md-9">
    <%= form_tag search_friend_path, remote: true, method: :get do %>
      <div class="input-group mb-3">
        <%= text_field_tag :friend, params[:friend], placeholder:"Search name or e-mail", autofocus: true, class:"form-control form-control-lg" %>
        <div class="input-group-append">
          <%= button_tag (fa_icon 'search'), type: :submit, class:"btn btn-outline-success btn-lg" %>
        </div>
      </div>
    <% end %>

    <div id="friend-results"></div>

    <%= render 'friends/table' %>
  </div>
</div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="row">
  <div class="col-md-9">
    <%= form_tag search_stock_path, remote: true, method: :get do %>
      <div class="input-group mb-3">
        <%= text_field_tag :stock, params[:stock], class:"form-control form-control-lg", placeholder:"Enter desired ticker...", autofocus: true %>
        <div class="input-group-append">
          <%= button_tag type: :submit, class:"btn btn-outline-success btn-lg" do %>
            <%= fa_icon 'search' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div id="results"></div>

    <%= render 'stocks/table' %>
  </div>
</div>

app/views/users/show.html.erb
<h1>User Details</h1>

<div class="row">
  <div class="col-md-9">
    <div class="card shadow mb-4" style="max-width: fit-content;">
      <table class="table">
        <tbody>
            <tr class="text-center">
              <td><strong>Name: </strong><%= @user.full_name %></td>
              <td><strong>Email: </strong><%= @user.email %></td>
              <td>
                <% if current_user.not_friends_with?(@user.id) %>
                  <%= link_to (fa_icon 'plus'), friendships_path(friend: @user), method: :post, class:"btn btn-warning btn-sm", title:"Follow User" %>
                <% else %>
                  <%= fa_icon 'check', class:"btn btn-success btn-sm", title:"You're already friends!" %>
                <% end %>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
    <%= render 'stocks/table' %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="invest jumbotron text-center">
  <h1>Welcome to the Finance Tracker app</h1>
  <hr>
  <h4>Monitor your investments and watch your friends stocks!</h4>
  <p><%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary btn-lg m-3" %></p>
</div>